#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x85199DE8C6648E90 (blp@gnu.org)
#
Name     : pspp
Version  : 1.4.1
Release  : 3
URL      : https://mirrors.kernel.org/gnu/pspp/pspp-1.4.1.tar.gz
Source0  : https://mirrors.kernel.org/gnu/pspp/pspp-1.4.1.tar.gz
Source1  : https://mirrors.kernel.org/gnu/pspp/pspp-1.4.1.tar.gz.sig
Summary  : a program for statistical analysis of sampled data
Group    : Development/Tools
License  : CC-BY-SA-3.0 GPL-3.0
Requires: pspp-bin = %{version}-%{release}
Requires: pspp-data = %{version}-%{release}
Requires: pspp-info = %{version}-%{release}
Requires: pspp-lib = %{version}-%{release}
Requires: pspp-license = %{version}-%{release}
Requires: pspp-locales = %{version}-%{release}
Requires: pspp-man = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : glibc-locale
BuildRequires : graphviz
BuildRequires : ncurses-dev
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gsl)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(gtksourceview-3.0)
BuildRequires : pkgconfig(libssl)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(pango)
BuildRequires : pkgconfig(pangocairo)
BuildRequires : pkgconfig(spread-sheet-widget)
BuildRequires : postgresql-dev
BuildRequires : readline-dev
BuildRequires : ssw-dev
BuildRequires : texinfo

%description
PSPP is a program for statistical analysis of sampled data.  It is
a free replacement for the proprietary program SPSS.

%package bin
Summary: bin components for the pspp package.
Group: Binaries
Requires: pspp-data = %{version}-%{release}
Requires: pspp-license = %{version}-%{release}

%description bin
bin components for the pspp package.


%package data
Summary: data components for the pspp package.
Group: Data

%description data
data components for the pspp package.


%package doc
Summary: doc components for the pspp package.
Group: Documentation
Requires: pspp-man = %{version}-%{release}
Requires: pspp-info = %{version}-%{release}

%description doc
doc components for the pspp package.


%package info
Summary: info components for the pspp package.
Group: Default

%description info
info components for the pspp package.


%package lib
Summary: lib components for the pspp package.
Group: Libraries
Requires: pspp-data = %{version}-%{release}
Requires: pspp-license = %{version}-%{release}

%description lib
lib components for the pspp package.


%package license
Summary: license components for the pspp package.
Group: Default

%description license
license components for the pspp package.


%package locales
Summary: locales components for the pspp package.
Group: Default

%description locales
locales components for the pspp package.


%package man
Summary: man components for the pspp package.
Group: Default

%description man
man components for the pspp package.


%prep
%setup -q -n pspp-1.4.1
cd %{_builddir}/pspp-1.4.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1600987285
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1600987285
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pspp
cp %{_builddir}/pspp-1.4.1/COPYING %{buildroot}/usr/share/package-licenses/pspp/842745cb706f8f2126506f544492f7a80dbe29b3
cp %{_builddir}/pspp-1.4.1/perl-module/COPYING %{buildroot}/usr/share/package-licenses/pspp/842745cb706f8f2126506f544492f7a80dbe29b3
cp %{_builddir}/pspp-1.4.1/src/ui/gui/icons/COPYING_CCBYSA3 %{buildroot}/usr/share/package-licenses/pspp/2995e7d53219d710383087253fb9a1e760e44f35
%make_install
%find_lang pspp

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pspp
/usr/bin/pspp-convert
/usr/bin/pspp-dump-sav
/usr/bin/pspp-output
/usr/bin/psppire

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.fsf.pspp.desktop
/usr/share/icons/hicolor/16x16/apps/pspp.png
/usr/share/icons/hicolor/16x16/mimetypes/application-x-spss-por.png
/usr/share/icons/hicolor/16x16/mimetypes/application-x-spss-sav.png
/usr/share/icons/hicolor/16x16/mimetypes/application-x-spss-sps.png
/usr/share/icons/hicolor/16x16/mimetypes/application-x-spss-zsav.png
/usr/share/icons/hicolor/22x22/mimetypes/application-x-spss-por.png
/usr/share/icons/hicolor/22x22/mimetypes/application-x-spss-sav.png
/usr/share/icons/hicolor/22x22/mimetypes/application-x-spss-sps.png
/usr/share/icons/hicolor/22x22/mimetypes/application-x-spss-zsav.png
/usr/share/icons/hicolor/24x24/mimetypes/application-x-spss-por.png
/usr/share/icons/hicolor/24x24/mimetypes/application-x-spss-sav.png
/usr/share/icons/hicolor/24x24/mimetypes/application-x-spss-sps.png
/usr/share/icons/hicolor/24x24/mimetypes/application-x-spss-zsav.png
/usr/share/icons/hicolor/256x256/apps/pspp.png
/usr/share/icons/hicolor/256x256/mimetypes/application-x-spss-por.png
/usr/share/icons/hicolor/256x256/mimetypes/application-x-spss-sav.png
/usr/share/icons/hicolor/256x256/mimetypes/application-x-spss-sps.png
/usr/share/icons/hicolor/256x256/mimetypes/application-x-spss-zsav.png
/usr/share/icons/hicolor/32x32/apps/pspp.png
/usr/share/icons/hicolor/32x32/mimetypes/application-x-spss-por.png
/usr/share/icons/hicolor/32x32/mimetypes/application-x-spss-sav.png
/usr/share/icons/hicolor/32x32/mimetypes/application-x-spss-sps.png
/usr/share/icons/hicolor/32x32/mimetypes/application-x-spss-zsav.png
/usr/share/icons/hicolor/48x48/apps/pspp.png
/usr/share/icons/hicolor/48x48/mimetypes/application-x-spss-por.png
/usr/share/icons/hicolor/48x48/mimetypes/application-x-spss-sav.png
/usr/share/icons/hicolor/48x48/mimetypes/application-x-spss-sps.png
/usr/share/icons/hicolor/48x48/mimetypes/application-x-spss-zsav.png
/usr/share/icons/hicolor/scalable/apps/pspp.svg
/usr/share/metainfo/org.fsf.pspp.metainfo.xml
/usr/share/mime-packages/pspp.xml
/usr/share/pspp/aggregate.ui
/usr/share/pspp/autorecode.ui
/usr/share/pspp/barchart.ui
/usr/share/pspp/binomial.ui
/usr/share/pspp/chi-square.ui
/usr/share/pspp/comments.ui
/usr/share/pspp/compute.ui
/usr/share/pspp/correlation.ui
/usr/share/pspp/count.ui
/usr/share/pspp/crosstabs.ui
/usr/share/pspp/data-editor.ui
/usr/share/pspp/descriptives.ui
/usr/share/pspp/entry-dialog.ui
/usr/share/pspp/examine.ui
/usr/share/pspp/examples/descript.sps
/usr/share/pspp/examples/grid.sps
/usr/share/pspp/examples/hotel.sav
/usr/share/pspp/examples/physiology.sav
/usr/share/pspp/examples/regress.sps
/usr/share/pspp/examples/regress_categorical.sps
/usr/share/pspp/examples/repairs.sav
/usr/share/pspp/examples/t-test.sps
/usr/share/pspp/factor.ui
/usr/share/pspp/find.ui
/usr/share/pspp/frequencies.ui
/usr/share/pspp/goto-case.ui
/usr/share/pspp/histogram.ui
/usr/share/pspp/indep-samples.ui
/usr/share/pspp/k-independent.ui
/usr/share/pspp/k-means.ui
/usr/share/pspp/k-related.ui
/usr/share/pspp/ks-one-sample.ui
/usr/share/pspp/logistic.ui
/usr/share/pspp/means.ui
/usr/share/pspp/missing-val-dialog.ui
/usr/share/pspp/oneway.ui
/usr/share/pspp/options.ui
/usr/share/pspp/output-window.ui
/usr/share/pspp/paired-samples.ui
/usr/share/pspp/pspp.lang
/usr/share/pspp/rank.ui
/usr/share/pspp/recode.ui
/usr/share/pspp/regression.ui
/usr/share/pspp/reliability.ui
/usr/share/pspp/roc.ui
/usr/share/pspp/runs.ui
/usr/share/pspp/scatterplot.ui
/usr/share/pspp/select-cases.ui
/usr/share/pspp/sort.ui
/usr/share/pspp/splash.png
/usr/share/pspp/split-file.ui
/usr/share/pspp/syntax-editor.ui
/usr/share/pspp/t-test.ui
/usr/share/pspp/text-data-import.ui
/usr/share/pspp/transpose.ui
/usr/share/pspp/univariate.ui
/usr/share/pspp/val-labs-dialog.ui
/usr/share/pspp/var-type-dialog.ui
/usr/share/pspp/variable-info.ui
/usr/share/pspp/weight.ui

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/pspp/*

%files info
%defattr(0644,root,root,0755)
/usr/share/info/pspp-dev.info
/usr/share/info/pspp-dev.info-1
/usr/share/info/pspp-dev.info-2
/usr/share/info/pspp.info
/usr/share/info/pspp.info-1
/usr/share/info/pspp.info-2

%files lib
%defattr(-,root,root,-)
/usr/lib64/pspp/libpspp-1.4.1.so
/usr/lib64/pspp/libpspp-core-1.4.1.so
/usr/lib64/pspp/libpspp-core.so
/usr/lib64/pspp/libpspp.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pspp/2995e7d53219d710383087253fb9a1e760e44f35
/usr/share/package-licenses/pspp/842745cb706f8f2126506f544492f7a80dbe29b3

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/pspp-convert.1
/usr/share/man/man1/pspp-dump-sav.1
/usr/share/man/man1/pspp-output.1
/usr/share/man/man1/pspp.1
/usr/share/man/man1/psppire.1

%files locales -f pspp.lang
%defattr(-,root,root,-)

